version: '3.4'
name: nuxt-trustup-io-translations
services:
  app:
    container_name: nuxt-trustup-io-translations-app
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - ${APP_PORT:-3000}:${APP_PORT:-3000}
      - ${WEBSOCKET_PORT:-24678}:${WEBSOCKET_PORT:-24678}
    volumes:
      - ./:/app